pipeline {
    agent any

    tools {
        maven 'Maven 3.8.1' // Ensure Maven is installed and configured in Jenkins
        jdk 'JDK 17'       // Ensure JDK 17 is installed and configured in Jenkins
    }

    stages {
        stage('Build') {
            steps {
                echo 'Building...'
                git branch: 'main', url: 'https://github.com/vernere/JenkinsTest.git'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing...'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
            }
        }
    }

}